[versions]
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.1"
kotlinx-serialization = "1.3.0"
androidxComposeCompiler = "1.3.0"
androidx-activity = "1.3.1"
androidx-compose = "1.3.0-alpha01"
jbComposeRuntime = "1.2.0"
lint = "30.4.0-alpha09"
zipline = "0.9.7"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-coreNativeMultithreading = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.1-native-mt" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

xmlutil-serialization = 'io.github.pdvrieze.xmlutil:serialization:0.84.2'

dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.7.10"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:6.8.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.22.0"
buildConfigPlugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"

androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx.activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }

google-material = { module = "com.google.android.material:material", version = "1.4.0" }

jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jbComposeRuntime" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "7.3.0" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
clikt = { module = "com.github.ajalt.clikt:clikt", version = "3.1.0" }
junit = { module = "junit:junit", version = "4.13.1" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.1" }
truth = { module = "com.google.truth:truth", version = "1.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9" }
okio = { module = "com.squareup.okio:okio", version = "3.1.0" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version = "4.9.1" }
zipline = { module = "app.cash.zipline:zipline", version.ref = "zipline" }
zipline-gradlePlugin = { module = "app.cash.zipline:zipline-gradle-plugin", version.ref = "zipline" }
zipline-loader = { module = "app.cash.zipline:zipline-loader", version.ref = "zipline" }
paparazzi-gradlePlugin = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version = "1.1.0" }
jimfs = "com.google.jimfs:jimfs:1.2"
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.2.2" }
coil-core = { module = "io.coil-kt:coil", version = "2.2.2" }

lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
